### ISSUE TITLE
Hacking MIFARE Classic Cards

### ISSUE THREAD

**Issue by bettse** [doegox/awesome-rfid-talks#7]
I can't do the PR at the moment, but I wanted to add a note that I think this pdf from a regional blackhat presentation ( https://www.blackhat.com/docs/sp-14/materials/arsenal/sp-14-Almeida-Hacking-MIFARE-Classic-Cards-Slides.pdf ) is great as introductory material about MFC.

**Comment by doegox** [comment]
Thanks! But note that this is a list of videos, not slides. I've added this one from the same author and year : 
* Ekoparty 2014 - [Hacking RFID Billing Schemes For Fun and Free Rides - Márcio Almeida](https://www.youtube.com/watch?v=epSJvZLO16Q)
